# Generated by Django 5.0 on 2024-01-03 18:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='reg_date',
            field=models.DateField(default=datetime.datetime(2024, 1, 3, 18, 31, 45, 386115)),
        ),
    ]
