# Generated by Django 5.0 on 2024-01-03 18:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_task_reg_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='reg_date',
            field=models.DateField(default=datetime.datetime(2024, 1, 3, 18, 32, 27, 933484), null=True),
        ),
    ]
