# Generated by Django 5.0 on 2024-01-03 18:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_alter_task_reg_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='reg_date',
            field=models.DateField(default=django.utils.timezone.now, null=True),
        ),
    ]
